apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cgx-nifi-platform
  namespace: argocd
spec:
  description: CGX NiFi China-France DB sync platform

  sourceRepos:
    - 'https://github.com/radhouen/nifi-devops-platform.git'

  destinations:
    - namespace: nifi-france
      server: https://kubernetes.default.svc
    - namespace: nifi-china
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace

  namespaceResourceWhitelist:
    - group: 'apps'
      kind: StatefulSet
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: 'networking.k8s.io'
      kind: Ingress

  roles:
    - name: read-only
      description: Read-only access to CGX NiFi apps
      policies:
        - p, proj:cgx-nifi-platform:read-only, applications, get, cgx-nifi-platform/*, allow
