prometheus:
  server:
    persistentVolume:
      size: 5Gi
    retention: 7d
  extraScrapeConfigs: |
    - job_name: 'nifi'
      static_configs:
        - targets: ['nifi-france-qa.svc.cluster.local:9092']
      metrics_path: /metrics
environment: qa
region: france
