prometheus:
  server:
    persistentVolume:
      size: 20Gi
    retention: 30d
  extraScrapeConfigs: |
    - job_name: 'nifi'
      static_configs:
        - targets: ['nifi-china-prod.svc.cluster.local:9092']
      metrics_path: /metrics
environment: prod
region: china
