apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifi-registry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cgx-nifi
  source:
    repoURL: https://github.com/radhouen/nifi-devops-platform.git
    targetRevision: HEAD
    path: helm/nifi-registry
  destination:
    server: https://kubernetes.default.svc
    namespace: nifi-france
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        maxDuration: 5m
        factor: 2
