apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifi-china
  namespace: argocd
  labels:
    region: china
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cgx-nifi
  source:
    repoURL: https://github.com/radhouen/nifi-devops-platform.git
    targetRevision: HEAD
    path: helm/nifi
    helm:
      valueFiles:
        - values-china.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nifi-china
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 30s
        maxDuration: 3m
        factor: 2
