apiVersion: v2
name: grafana
description: Grafana dashboards for CGX NiFi platform
type: application
version: 0.1.0
dependencies:
  - name: grafana
    version: "8.x.x"
    repository: https://grafana.github.io/helm-charts
