apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nifi.fullname" . }}-config
  labels:
    {{- include "nifi.labels" . | nindent 4 }}
data:
  NIFI_WEB_HTTP_PORT: {{ .Values.service.port | quote }}
  NIFI_CLUSTER_IS_NODE: "true"
  REGION: {{ .Values.region.name | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nifi.fullname" . }}-flow
  labels:
    {{- include "nifi.labels" . | nindent 4 }}
binaryData:
  flow.json.gz: ""
